### ISSUE TITLE
[FYI] - Style name "Autocomplete" added to popular extension a1111-sd-webui-tagcomplete to allow for easier recall of style names while prompting - Works in tandem w/ this extension (noted)

### ISSUE THREAD

**Issue by CCpt5** [SirVeggie/extension-style-vars#1]
Just an FYI that the developer of [a1111-sd-webui-tagcomplete](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) has kindly added support for Style name completion per a request and the new availability of this app which it works best in tandem with (noted). Thread: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/268

**Comment by SirVeggie** [comment]
Great, I've been thinking about autocomplete too, so this is perfect. Thanks for informing me.
