### ISSUE TITLE
When doing a batch, randomization syntax does not work.

### ISSUE THREAD

**Issue by ICodeDiffusion** [SirVeggie/extension-style-vars#3]
When I choose to do a batch(not the multiple in one) with the syntax {one|two|three} and it makes multiple images, it does not randomize, I have to have it run non-stop image by image.

Is their any way you can fix it? or is it an easy fix that maybe I can pull off (barely no coding experience).

**Comment by SirVeggie** [comment]
I don't seem to have the same problem. Both batch count and batch size settings produce images with different random options. Have you tried turning off all other extensions?

**Comment by SirVeggie** [comment]
Closed due to inactivity.
